### PR TITLE
Pr2

### PR DESCRIPTION
**Pull request by w3guy**

### CODE REVIEW

**Comment by afragen** [comment]
I see you've gone back to trying to load the class from within the class file. This only works in your example plugin and doesn't result in the javascript file being loaded when the class is loaded via an autoloader. The reason your test plugin works is that the `require` runs if the plugin is active and runs on every page load or every admin page load, not quite certain. With autoloaders this won't happen.

That's the reason I've switched around the instantiation to require

```
add_action( 'admin_init', array( PAnD::instance(), 'init' ) );
```

is than here the javascript is loaded. It took me a while to _see_ this issue.

I see our 2 IDE's are fighting with WP Coding Guidelines regarding spacing. I'm using PhpStorm with the WordPress guidelines installed. https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml#L105-L155

There's really no reason to call `is_admin_notice_active()` as a static and doing so will make the function untestable in the future.

Does this make sense?

**Comment by afragen** [comment]
And there's this about variable alignment.

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation

**Comment by w3guy** [comment]
I agree with your first sentiment. Will get this reverted.

For the second, we can always make assertion with a static method should we
incorporate test. No?

Regarding the code standard, I kinda prefer psr2 code style. Will revert my
editor to WordPress coding standard for this project.

**Comment by afragen** [comment]
> For the second, we can always make assertion with a static method should we
> incorporate test. No?

I honestly don't know. Creating unit tests is one of the things on my learning _@TODO_ list. 😉 
http://stackoverflow.com/questions/5961023/unit-testing-and-static-methods
I try not to make my life more difficult in the future and avoiding statics for potentially testable code is a way to do this.

> I agree with your first sentiment. Will get this reverted.

You don't need to revert, just use my PR. Without this change and using the same spacing guidelines I'm using, or trying to use, results in no changes from the initial PR. Except for your `.gitignore`.

**Comment by w3guy** [comment]
Am not new to unit test evident in my OmniPay drivers public repository.

Static method is a pain only when you fail to set up its dependency in
Phpunit setup method.

Changing to static method is the only ch she that I intend to make to your
PR

**Comment by afragen** [comment]
Would you like me to do it?

**Comment by afragen** [comment]
Not sure we'll need the `instance` method then. Do you want me to remove or leave it?

**Comment by w3guy** [comment]
Not sure we will be needing it. Remove it.

Should we tag this version 2.0 or 1.2?

**Comment by afragen** [comment]
We will need `instance` for

```
add_action( 'admin_init', array( PAnD::instance(), 'init' ) );
```

> Should we tag this version 2.0 or 1.2?

I would go with 1.0 or 2.0 depending upon how widespread you think this project has been in use. LMK and I'll adjust the PR

**Comment by w3guy** [comment]
Why not we make init a static method so we end up with below

add_action( 'admin_init', array( 'PAnD', 'init' ) );

**Comment by afragen** [comment]
That would require a change of `init()` to not use `$this` as well. Are we changing things now for the sake of changing them or does this make the use easier?

The user is really going to copy/paste the hook from the readme anyway.

**Comment by w3guy** [comment]
Am all for making things easier for users and making using the library as
expressive and easy as possible.

Am sure it is doable.

Your thought.

**Comment by w3guy** [comment]
And by the way, thanks for all your hardwork and time.

**Comment by afragen** [comment]
I don't really think it makes a difference. The users of this library will know what it means and I don't think there is any overhead difference. It's stylistic and it's your repo. Anything's doable.

Let me know how you want it and what version number to use.

**Comment by w3guy** [comment]
I will prefer the init method is static.

Please tag it as 1.1

I can see you are already using it in your github updater plugin. :smile:

**Comment by afragen** [comment]
Done.

That version of GitHub Updater hasn't been released. 😉 
Still want 1.1?

**Comment by afragen** [comment]
BTW, to avoid PHP notices every method will end up being `static` if we remove the singleton. Do you wish to proceed with it?

**Comment by afragen** [comment]
My preference would be to use statics where they make sense, not just to use them. I think we should revert back to using the singleton and non-static loading.

I think the code is cleaner.

**Comment by w3guy** [comment]
I think it perfectly make sense to use static methods in this case.

This is a small library with no serious initialization being done when
class is instantiated.

Not only you, but a lot of Dev I come across always try to avoid static
methods as much as possible.

This is a scenario where it perfectly make sense.

**Comment by w3guy** [comment]
Yes please. Make all methods static or better still, to not make all the
methods static, how about we add the

add_action( 'admin_init', array( PAnD::instance(), 'init' ) );

Inside a function in the class so that calling say

PAnD::init()

Registers the scripts and all other things in

array( PAnD::instance(), 'init' )

By so doing, we reduce the code for botstrapping the library.

**Comment by afragen** [comment]
OK, my PR now completely static, no PHP errors and tagged version 1.1.0

> add_action( 'admin_init', array( PAnD::instance(), 'init' ) );
> 
> Inside a function in the class so that calling say
> 
> PAnD::init()
> 
> Registers the scripts and all other things in
> 
> array( PAnD::instance(), 'init' )
> 
> By so doing, we reduce the code for botstrapping the library.

I don't think we can do this as the initial problem of loading outside of the class is needed. It also adds a lot of complexity.

I think we should either stick with all static or add singleton back.

PR now stands as all static, but I can revert.

**Comment by w3guy** [comment]
All static is fine. Let me review now.

**Comment by w3guy** [comment]
Thanks for all the hardwork. 1.1.0 is now live.

**Pull request closed without merging**
