### PR TITLE
add version to composer.json

### PR DESCRIPTION
**Pull request by afragen**

### CODE REVIEW

**Comment by afragen** [comment]
And I added it to the composer.json. Just so that we don't need to arbitrarily bump the class file if nothing changes there.

**Comment by w3guy** [comment]
Didn't see this on time. I will check on this much later.

**Comment by afragen** [comment]
It’s really just a way to add the version number to something other than the main framework file. Once here it can be removed from the main php file. 

Yes, now it would need to be bumped. 😉

**Comment by w3guy** [comment]
I will keep this mind if there is another update

**Comment by Remzi1993** [comment]
Hi @w3guy 
Is this also going to be implemented? This would help in pushing updates and making development easier.
Also for some to stick to a specific version for whatever reason.

Kind regards,
Remzi

**Comment by Remzi1993** [comment]
Hi @w3guy,

I think this is ready to be merged. Could you kindly merge this?

Kind regards,
Remzi

**Comment by w3guy** [comment]
@Remzi1993 done.

**Comment by Remzi1993** [comment]
@w3guy Thank you so much!

**Pull request merged**
