### PR TITLE
use transient instead of option

### LINKED ISSUE #7: Theoretical collision
It's possible that 2 or more notices have the same name and collisions will result. I played with adding a hash but it wouldn't work as a static.

I'm still playing with it.

### PR DESCRIPTION
**Pull request by afragen**
uses AUTH_COOKIE as salt. This should fix #7

### CODE REVIEW

**Comment by w3guy** [comment]
Will test and get back to you. In the mean time, can you update the readme as stated in #5

**Comment by afragen** [comment]
After sleeping on it I'm now sure the salt is needed.

**Comment by afragen** [comment]
> Will test and get back to you. In the mean time, can you update the readme as stated in #5

Done. https://github.com/collizo4sky/persist-admin-notices-dismissal/commit/b986715ea7d8151e5c66ea16487eada09b0f65f6

**Comment by afragen** [comment]
I've been testing and it seems to work great. I think using transients will be preferable so we don't leave lots of clutter in the options table.

**Comment by w3guy** [comment]
Could you please merge this and i will get it tagged and released tomorrow.

**Comment by w3guy** [comment]
Released 😄

**Pull request merged**
