### PR TITLE
Use options not transients

### PR DESCRIPTION
**Pull request by afragen**
Hopefully this plays nicer with object caching.
Fixes https://github.com/collizo4sky/persist-admin-notices-dismissal/issues/17

### CODE REVIEW

**Comment by afragen** [comment]
Just need to remember to tag release `1.4.0`

**Comment by afragen** [comment]
@collizo4sky Hold off on merging. I thought of a slightly better plan to put all the options in single array. It will make cleanup simpler.

**Comment by w3guy** [comment]
I’ll hold

**Comment by afragen** [comment]
Go ahead. It was getting overly complex for the perceived gain.

**Comment by afragen** [comment]
@collizo4sky this works for me, OK for merge after your review. Please remember to tag release. 😉

**Comment by w3guy** [comment]
I'll test now and merge.

**Pull request merged**
