### PR TITLE
Fixes by WPCS

### PR DESCRIPTION
**Pull request by ghost**
- Version parameter is not explicitly set or has been set to an equivalent of "false" for wp_enqueue_script; This means that the WordPress core version will be used which is not recommended for plugin or theme development. (WordPress.WP.EnqueuedResourceParameters.NoExplicitVersion)
- Detected usage of a possibly undefined superglobal array index: $_POST['option_name']. Use isset() or empty() to check the index exists before using it (WordPress.Security.ValidatedSanitizedInput.InputNotValidated)
- Detected usage of a possibly undefined superglobal array index: $_POST['dismissible_length']. Use isset() or empty() to check the index exists before using it (WordPress.Security.ValidatedSanitizedInput.InputNotValidated)

### CODE REVIEW

**Comment by afragen** [comment]
There were also a number of other WPCS issues. I've included some modifications to your PR and the other updates in #36

**Comment by w3guy** [comment]
Fixed in #36

**Comment by Surbma** [comment]
@w3guy The first WPCS error is not fixed:

Version parameter is not explicitly set or has been set to an equivalent of "false" for wp_enqueue_script; This means that the WordPress core version will be used which is not recommended for plugin or theme development. (WordPress.WP.EnqueuedResourceParameters.NoExplicitVersion)

Please use the version number instead of "false".

**Comment by w3guy** [comment]
@Surbma please submit a pull request

**Comment by Surbma** [comment]
@w3guy Original PR was already sent with this fix, but I just submitted a new PR with this fix. Thank you!

**Pull request closed without merging**
