### PR TITLE
Refactor as class and other things

### PR DESCRIPTION
**Pull request by afragen**
I've done a large refactor of the library by putting it in a class. This has a couple of advantanges. Below is a summary of the changes.
- this will allow Composer to use it's autoloader for the class
- added exits for direct calling of class, calling during heartbeat, and if `class_exists()`
- I included a `.gitattributes` file to exclude dev stuff from a direct download.
- I updated the README to refer to a framework library and updated the examples.
- spacing per WP Coding Guidelines.
- switched to Yoda conditionals.
- removed anonymous functions and shorthand array declaration, it should be PHP 5.2 compatible now. Since we didn't use namespacing there's not much need to limit ourselves.
- fixed the nonce check so it works 👍 
- in the Docblock, I added myself as an author and included a version number

You've done a great job, thanks!

Let me know if there is anything else I can do for the PR or if this really isn't the direction you wanted to go.

BTW, I'm not really good with `composer.json` and I don't know if any changes need to be made there.

### CODE REVIEW

**Comment by afragen** [comment]
Hold off merging for a while. This works locally but doesn't seem to work on test server. 😝

**Comment by afragen** [comment]
The scripts don't seem to load on my test server. I know `__construct()` runs but the javascript isn't loaded on the page.

**Comment by afragen** [comment]
Everything seems to be working now. The issue I had was that loading the class in the `admin_notices` hook was after the `admin_enqueue_script` hook already fired. This only for autoloaders.

I added more instructions in the README for the proper method to load and call the class.

**Comment by afragen** [comment]
@collizo4sky even if you haven't gotten around to reviewing this PR, please look at the last commit. Without fixing this every dismissal is effectively 'forever'
https://github.com/collizo4sky/persist-admin-notices-dismissal/pull/2/commits/62a8924ddd6f28ec483cc7f143c40cab2a478046

**Comment by w3guy** [comment]
Thanks alot for this. I will review before the end of today (5:52 AM here).

**Comment by afragen** [comment]
Let me know if you have questions, though time for 😴 here.

**Comment by w3guy** [comment]
Ooops. I should get to this on or before this weekend. School work taking ample of my time.

**Comment by afragen** [comment]
No hurry. I just found another issue that I fixed. 

`add_option` doesn't allow updates so when a one day dismissal ends there's no way to dismiss again. I changed it to `update_option` and I'm testing, but it should work.

**Comment by w3guy** [comment]
Hi, i made a few changes to the codebase and the readme. Could you please go over #3 and let me know your thoughts?

Note: library now automatically instantiated on plugins_loaded hook. One less of code line to use it.

**Pull request merged**
